CFLAGS=-I /usr/local/include
YACC=bison -y
LEX=flex
LFLAGS=-i -L
YFLAGS=-d
LDFLAGS=-lnort -lph
OBJ=llop.o opnifile.o oui.o ouiinit.o ouimain.o output.o sortpkg.o yylex.o
SRC=llop.c opnifile.c oui.y ouiinit.c ouimain.c output.c sortpkg.c yylex.l
oui : $(OBJ)


