DATA=QCLI.agm
DATA+=qcli.tmc.in
DATA+=qcli_col.tmc.in
DATA+=qcli_conv.tmc.in
DATA+=qcli_types.tmc
DATA+=qclia.cmd
DATA+=qclis.cmd.in
DATA+=qcli.tbl.in
DATA+=qcli.genui.in
DATA+=ssp_amp.AB3R.tmc.in
DATA+=ssp_noise.AB3R.tmc.in
DATA+=ssp_amp.genui.in
DATA+=ssp_noise.genui.in
DATA+=ssp_amp_col.tmc.in
INC=qclisspcmd.h

install :
	@cp -vn $(DATA) /usr/local/share/huarp/
	@cp -vn $(INC) /usr/local/include/
