#define DCCC "dccc"

/*	dccc receives msgs of maximum size MAX_DCCC_MSG_SZ.
        they can be of the following form, each 1 byte:

                DASCMD DCT_QUIT DCV_QUIT
                DASCMD DCT_DCCC STROBEcmd/STEPcmd
                DC_MULTCMD #cmds STROBEcmd ...
                DC_MULTCMD #cmds STEPcmd ...
                DC_MULTCMD #cmds SETcmd hi-byte-value lo-byte-value ...
                DC_MULTCMD #cmds SELECTcmd hi-byte-value lo-byte-value ...
*/	
