#! /bin/sh
function nl_error {
  echo "chkpkgs: $*" >&2
  exit 1
}

{ if [ x"$1" != x ]; then
    for i in $*; do
      echo pkgs/$i/Header
    done
  else
    find pkgs -name Header
  fi
} |
while read hdr; do
  pkg=${hdr%/Header}
  echo "Checking $pkg"
  grep "^Files:" $hdr |
  while read fline; do
    fline=${fline#Files: }
    manif=${fline% @*}
    root=${fline#*@ }
    case $root in
      */) ;;
      *) root="$root/";;
    esac
    if [ ! $manif = MANIFEST_pkg ]; then
      [ -f $pkg/$manif ] || nl_error "Cannot locate $pkg/$manif"
      while read fspec; do
	if [ ! -d $root$fspec -a ! -f $root$fspec -a ! -h $root$fspec ]; then
	  echo "$pkg/$manif: File not found: $root$fspec"
	fi
      done < $pkg/$manif
    fi
  done
done

