#! /bin/sh
function nl_error {
  echo "chkpkgs: $*" >&2
  exit 1
}

find pkgs -name Header |
while read hdr; do
  pkg=${hdr%/Header}
  grep "^Files:" $hdr |
  while read fline; do
    fline=${fline#Files: }
    manif=${fline% @*}
    root=${fline#*@ }
    case $root in
      */) ;;
      *) root="$root/";;
    esac
    [ -f $pkg/$manif ] || nl_error "Cannot locate $pkg/$manif"
    while read fspec; do
      if [ -d $root$fspec ]; then
	echo "$pkg/$manif: Directory $root $fspec"
      elif [ ! -f $root$fspec ]; then
	echo "$pkg/$manif: File not found: $root $fspec"
      fi
    done < $pkg/$manif
  done
done

