#! /bin/sh
#
# mkrtkit pkg
function nl_error {
  echo "mkrtkit: $*" >&2
  exit 1
}

pkg=$1
[ -n "$pkg" ] || nl_error No package specified

# This needs a lot of work
#   could skip initializing the working directory if it already exists
#   Decide how to specify what packages to include (command line)
#
# Make a working directory and change into it:
[ -d rtkit_image ] || mkdir rtkit_image
cd rtkit_image

# Create the required directory repository and boot/fs:
[ -d repository ] || mkdir -p repository
rm -f repository/*
[ -d boot/fs ] || mkdir -p boot/fs

# Should probably stow this stuff on a non-CD somewhere
# Copy the following required files from the original Installation and Boot CD to working_dir/boot/fs:
cp -n /fs/cd0/boot/fs/qnxbase.qfs /fs/cd0/boot/fs/*.ifs ./boot/fs

# Copy the Runtime Kit version of the CD boot image (instflop-rtkit.dat) from the
# rtkit directory in the root directory of the Installation and Boot CD to the
# working_dir directory:
cp -n /fs/cd0/rtkit/instflop-rtkit.dat ./instflop.dat

# Create or copy the installation script and call it rtinstall.
cp /usr/local/share/huarp/rtinstall .
chmod a+x ./rtinstall

# This is the configuration-specific part of the script.
# Copy each of the archives you created earlier to ./repository:
mkrtkitarch repository $pkg || nl_error mkrtkitarch failed

mkisofs -r -b instflop.dat -c boot/isocatalog -J -o ../rtkit-$pkg.iso .
cd ..
# rm -r rtkit_image
