#! /bin/sh
function nl_error {
  echo "restore_cache_times: $*" >&2
  exit 1
}

tdir=/var/huarp/pkgcache/times
[ -d $tdir ] || nl_error $tdir not found
cd $tdir

for i in *.tar.gz; do
  if [ -f ../$i ]; then
    touch -r $i ../$i
  else
    echo "restore_cache_times: $i not found"
  fi
done

