#! /bin/sh
#ifdef __USAGE__
#%C <hostname>
#endif

function nl_error {
  echo "synch_to_remote: $*" >&2
  exit 1
}

tgt=$1
dryrun=''
if [ "X$tgt" = "X-n" ]; then
  dryrun='--dry-run'
  tgt=$2
fi
[ -n "$tgt" ] || nl_error Must specify target hostname
rsync -av --rsync-path=/usr/pkg/bin/rsync $dryrun \
  /var/huarp/pkgcache $tgt:/var/huarp

