BIN=decipher install_app mkpatch pic2html2 picscale txt2html word2txt \
    dircompare dircksum genui distill pic2html3 OrchClt
INSTALL=/usr/bin/install
#INSTALL=cp -v
install :
	$(INSTALL) $(BIN) /usr/local/bin

