#! /bin/sh

#__USAGE
#%C	[ofile [ifile]]
#	Generates a patch file for the application defined in
#	QNX.setup in the current directory. If a file is specified,
#	a patch for only that specific file is generated.
#	Files which have been added to the application must be listed
#	either in the "newfiles" variable or in QNX.newfiles.

function nl_error {
  echo mkpatch: $* >&2
  exit 1
}

[ -f QNX.setup ] || nl_error Cannot locate QNX.setup
portpath=`fullpath -t .`
portdir=`basename $portpath`
. QNX.setup

ofile=$1
pfile=$2
[ -z "$ofile" ] && ofile=$pkg
[ -z "$pkg" ] && nl_error pkg must be defined
[ -f $ofile.pat.F ] && nl_error $ofile.pat.F already exists
cd ..

[ -d "$pkg" ] || nl_error Cannot locate directory $pkg
[ -d "$pkg.ORIG" ] || nl_error Cannot locate directory $pkg.ORIG
[ -d "$portdir" -a -d "$portpath" ] ||
  nl_error Cannot locate original directory $portpath
echo "mkpatch: Comparing $pkg.ORIG to $pkg"
(
  if [ -n "$pfile" ]; then
	if [ -f $pkg.ORIG/$pfile -a -s $pkg.ORIG/$pfile ]; then
	  newfiles=''
	else
	  newfiles=$pfile
	fi
  elif [ -z "$newfiles" -a -f $portdir/QNX.newfiles ]; then
	newfiles=`cat $portdir/QNX.newfiles`
  fi
  if [ -n "$newfiles" ]; then
	for file in $newfiles; do
	  [ -f "$pkg.ORIG/$file" -a -s "$pkg.ORIG/$file" ] &&
		nl_error $pkg.ORIG/$file exists!
	  [ -f "$pkg/$file" ] || nl_error $pkg/$file missing
	  if [ -s "$pkg/$file" ]; then
		touch $pkg.ORIG/$file
		touched="$touched $pkg.ORIG/$file"
	  fi
	  echo "touch $file"
	done
  fi
  echo "exit 0\n=============\n"
  if [ -n "$pfile" ]; then
	ffile=$pkg.ORIG/$pfile
	file=$pkg/$pfile
	cmp -s $file $ffile || diff -c $ffile $file
  else
	for ffile in `find $pkg.ORIG \( -name RCS -prune \) -o \( -type f -print \)`; do
	  file=$pkg/${ffile#$pkg.ORIG/}
	  cmp -s $file $ffile || diff -c $ffile $file
	done
  fi
  [ -n "$touched" ] && rm $touched
) | freeze > $portdir/$ofile.pat.F
