#! /bin/sh
#ifdef __USAGE
# %c
#
# Displays any TM channels that are not displayed.

{
  sed -e '/bytes \(Datum\|Member\)/! d' \
      -e 's/^.*bytes \(Datum\|Member\) //' \
      -e 's/ (.*)//' *.pcm;
  sed -e 's/^#.*$//' -e 's/^.*=//' -e 's/[\t ]/\n/g' Makefile |
    grep '\.tmc$' | sort -u |
    xargs grep -i invalidate |
    sed -e 's/^.*[Ii]nvalidate //' \
	-e 's/;.*$//'
} | sort |
while read j; do
  grep -q "text($j)" *nc.tmc || echo $j
done

