#! /bin/sh

#__USAGE
#%C	[options] <image>
#	<image> is the name of the root directory, defaults to '.'
#	Checks a CD image for stuff.
#	Locates any .CKSUMs and checks them.
#	Searches for nefarious file names
#	Checks total size (du -sk doesn't work if soft-links are
#	                    included)
#  -L Allow oversized images
#  -s Don't create dircksum
allow_largeimage=no
do_dircksum=yes
while getopts "Ls" option; do
  case $option in
    L) allow_largeimage=yes;;
    s) do_dircksum=no;;
    \?) echo; exit 1;;
    *) echo Unsupported option: -$option; exit 1;;
  esac
done
let sval=$OPTIND-1
shift $sval

image=$1
[ -n "$1" ] || image="."

function nl_error {
  echo "prepCD: $*" >&2
  exit 1
}

[ -d $image ] || nl_error "Unable to locate directory '$image'"
[ -w $image -a -x $image ] ||
  nl_error "You don't have write and execute permissions for '$image'"

[ -z "$tmpfile" ] && tmpfile=/tmp/prepCD.$$
echo "Checking for invalid filenames or permissions:"
find $image -follow \( -name '*[~$# ]*' -o -name '.B4_*' \
  -o -name '[Aa][Uu][Xx]' -o -name '[Aa][Uu][Xx].*' \
  -o -name '[Cc][Oo][Mm][1-4]' -o -name '[Cc][Oo][Mm][1-4].*' \
  -o -name '[Ll][Pp][Tt][1-3]' -o -name '[Ll][Pp][Tt][1-3].*' \
  -o -name '[Pp][Rr][Nn]' -o -name '[Pp][Rr][Nn].*' \
  -o -name '[Nn][Uu][Ll]' -o -name '[Nn][Uu][Ll].*' \
  -o -name '[Cc][Oo][Nn]' -o -name '[Cc][Oo][Nn].*' \
  -o ! -perm -a+r \) -ls 2>&1 | tee $tmpfile
if [ -s $tmpfile ]; then
  echo "File list is saved in $tmpfile"
  exit 1
else
  echo "No files found, removing temp file $tmpfile"
  rm $tmpfile
fi

echo "Checking archive size:"
total=0
function recurse {
  for path in $*; do
    du=`du -sk $path`
    k=`expr "$du" : ' *\([0-9][0-9]*\)'`
    let total=$total+$k
    echo "$du"
    recurse `find $path -type l -printf "%l\n"`
  done
}
recurse $image
echo "Total size is $total K"
[ "$allow_largeimage" = "no" -a $total -gt 650000 ] &&
  nl_error "CD Image is probably too large: Use prepCD -L if you disagree"

echo "Checking existing .CKSUM and .MD5SUM files:"
find $image -follow -type d ! -level 0 \
     \( -exists "{}/.CKSUM" -o -exists "{}/.MD5SUM" \) |
  xargs nice dircksum | tee $tmpfile

echo "\nSummarizing dircksum results:"
egrep "Checksums are different|New values are in" $tmpfile ||
  echo "No discrepancies found"
if [ -s $tmpfile ]; then
  echo "Complete summary is in $tmpfile"
else
  rm $tmpfile
fi

if [ $do_dircksum = yes ]; then
  if [ ! -f $image/.CKSUM -a ! -f $image/.MD5SUM ]; then
    echo "Creating $image/.MD5SUM"
    cd $image
    nice dircksum -w . || {
      rm -f .CKSUM .MD5SUM
      nl_error "dircksum failed: .CKSUM and/or .MD5SUM deleted"
    }
  else
    echo "$image/.CKSUM or $image/.MD5SUM already exists"
  fi
else
  echo "Skipping dircksum as per -s"
fi
