usage "--help";
usage "-h";
usage "-?";
OutFile "-o" string "Write compiled QCLI code to specified file";
CmdFile "-c" string "Write cmd code to specified file";
MFile   "-m" string "Write Matlab waveform data to specified file";
DispFile "-d" string "Write display definitions to specified file";
VerbFile "-v" string "Write verbose summary to specified file";
terminator "--";
InputFile input "The file to be processed";
