#! /bin/sh
rm -rf newsrc
if [ ! -d newsrc ]; then
  mkdir newsrc
  eli "qclicomp.specs:source >newsrc"
fi
for i in src/*; do
  if [ "$i" != "src/makeqnx" -a -f $i -a ! -f "new$i" ]; then
    echo new$i does not exist
  fi
done
rm -f newsrc/obstack.[ch]
for i in newsrc/*; do
  j=${i#new}
  if [ -f "$j" ]; then
    if diff $j $i | grep "^[<>]" | grep -v -q "\$Id"; then
	  echo $i has changed
	  cp $i $j
    fi
  else
    echo $i is a new file
	cp $i $j
  fi
done
