include $(SRCDIR)/src.mk
BASE = sccfg
SUBDIRS =
HOMEDIR = $(SRCDIR)/diags/suite/$(BASE)
TXTS =
SRCS = sccfg.c
LIBS = curses lat curses_utils
HDRS = ../attribut.h
DOCS = scdiag.cfg

include $(SRCDIR)/tgt.mk
sccfg.o : sccfg.c ../attribut.h
