#! /bin/sh

# Bootstrap:
#  Download the source code:
# cd $BUILDROOT
# git clone git@github.com:nthallen/arp-das.git
# cd arp-das
# utils/FullTopBuild

# This expects to find the directories arranged as they are in
# the git repository. Specifically, it is looking for:

dirs=$(cat <<EOF
utils
nortutil
nortlib2
cmdgen
oui
tmlib
tmphlib
tmpplib
displib
drivers/subbus
tmutil
tmc
TMbfr/resmgr
lgr
rdr
memo
phrtg-native
tmcalgo
drivers/QCLI/qcliutil
drivers/subbus/subbusd
drivers/dccc
drivers/subbus/diag/diagnost
drivers/subbus/diag/diagsuite
drivers/DACS/DACSutil
drivers/soldrv
drivers/solfmt
drivers/specq
drivers/ssp_driver
drivers/idx64
drivers/hart
playback
drivers/oms
drivers/tmdf
drivers/versalogic
EOF
)

# This should be run in the root of the source tree, which might
# be ~/BUILD

function nl_error {
  echo FullTopBuild: $* >&2
  exit 1
}

alldirs=yes
for dir in $dirs; do
  if [ ! -d $dir ]; then
    echo "Directory $dir not found" >&2
    alldirs=no
  fi
done
[ $alldirs = yes ] || nl_error "Are you in the correct directory?"


if [ `id -u` != 0 ]; then
  exec sudo $0
  nl_error exec failed
fi

function logresult {
  dt=`date`
  echo "$dt: $*" >>FullTopBuild.log
  echo "$dt: $*"
  [ "$1" = "End" ] && echo >>FullTopBuild.log
}

function process {
  dir=$1
  shift
  curdir=$PWD
  [ -d $dir ] || nl_error "Directory '$dir' not found"
  cd $dir
  result=OK
  $* || result=FAIL
  cd $curdir
  logresult "$result $dir"
  rv=0
  [ $result = OK ] || rv=1
  return $rv
}

logresult Start
process utils make install || nl_error "Cannot continue"
process nortutil FullBuild install
OK=no
process nortlib2 FullBuild all &&
  process cmdgen FullBuild all &&
  process oui FullBuild all &&
  process tmlib FullBuild all &&
  process tmphlib FullBuild all &&
  process tmpplib FullBuild all &&
  process displib FullBuild all &&
  process drivers/subbus FullBuild all &&
  OK=yes
[ $OK = yes ] || nl_error "Cannot continue"
process tmutil FullBuild make install
process tmc FullBuild make install
process TMbfr/resmgr FullBuild make install
process lgr FullBuild make install
process rdr FullBuild make install
process memo FullBuild make install
process phrtg-native FullBuild make install
process tmcalgo FullBuild make install
process drivers/QCLI/qcliutil FullBuild make install
# process snafu FullBuild all
process drivers/subbus/subbusd FullBuild make install
process drivers/dccc FullBuild make install
process drivers/subbus/diag/diagnost FullBuild make install
process drivers/subbus/diag/diagsuite FullBuild make install
process drivers/DACS/DACSutil FullBuild make install
process drivers/soldrv FullBuild make install
process drivers/solfmt FullBuild make install
process drivers/specq FullBuild make install
process drivers/ssp_driver FullBuild make install
process drivers/idx64 FullBuild make install
process drivers/hart FullBuild make install
process playback FullBuild make install
process drivers/oms FullBuild make install
process drivers/tmdf FullBuild make install
process drivers/versalogic FullBuild install

# The eli build has been fixed, but it should probably be
# built before FullTopBuild
if which eli >/dev/null 2>&1; then
  process table FullBuild make install
  process qclicomp FullBuild make install
  process cycle FullBuild make install
else
  echo "eli not found: cycle, table and qclicomp not processed"
  echo "Build eli in order to finish installation, or"
  echo "consider using qclicompsrc"
  logresult table SKIPPED
  logresult qclicomp SKIPPED
  logresult cycle SKIPPED
fi

logresult "End"
echo FullTopBuild Processing Completed
echo Review FullTopBuild.log and also FullBuild logs in all
echo directories for more details.
