#! /bin/sh
#ifdef __USAGE
# sec_copy <tgtnode>
# example: sec_copy radflt
#
# Copies various security files to the designated node.
#endif

if [ `id -u` != 0 ]; then
  exec /usr/pkg/bin/sudo $0 $*
fi

function nl_error {
  echo "pkg_copy: $*" >&2
  exit 1
}

scrnode=''
if [ -n "$2" ]; then
  srcnode=$1
  shift
fi
tgtnode=$1
shift

[ -z "$tgtnode" ] && nl_error "Usage: sec_copy [<srcnode>] <tgtnode>"
[ -d /net/$tgtnode/ ] || nl_error "Cannot locate target node /net/$tgtnode"
ok=`on -f $tgtnode echo OK 2>&1`
[ "$ok" = "OK" ] || nl_error "$ok"

if [ -n "$srcnode" ]; then
  sn=/net/$srcnode
else
  sn=''
fi
tn=/net/$tgtnode
ood=''
for i in passwd group shadow; do
  [ $tn/etc/$i -nt $sn/etc/$i ] && ood="$ood /etc/$i"
done
[ $tn/usr/pkg/etc/sudoers -nt $sn/usr/pkg/etc/sudoers ] &&
  ood="$ood /usr/pkg/etc/sudoers"
[ $tn/etc/profile.d/pkg.sh -nt $sn/etc/profile.d/pkg.sh ] &&
  ood="$ood /etc/profile.d/pkg.sh"
if [ -n "$ood" ]; then
  echo "Some files on target node are newer than source:"
  for i in $ood; do
    echo "  $i"
  done
  exit 1
fi

cp -vn $sn/etc/passwd $sn/etc/group $sn/etc/shadow $tn/etc
on -f $tgtnode mkdir -p /usr/pkg/etc
cp -vn $sn/usr/pkg/etc/sudoers $tn/usr/pkg/etc/
cp -vn $sn/etc/profile.d/pkg.sh $tn/etc/profile.d
ln -fs pkg.sh $tn/etc/profile.d/pkg.ksh

