#! /usr/bin/perl -w
# Tool to generate definitions for digital command status

sub define_var {
  my ( $var, $src, $bit ) = @_;
  print "on_off_status $var; invalidate $var;\n";
  printf "{ %s = (%s & 0x%X) ? 1 : 0; validate %s; }\n",
    $var, $src, 1<<$bit, $var;
}

print <<EOF;
%{
  /* digio.tmc: generated by gen_digio.pl */
  static char *on_off_status_text[] = {
    "Off",
    "On "
  };
%}
TM typedef unsigned char on_off_status { text "%3d" on_off_status_text[]; }

EOF

# Cmd<n>DS for n = 0-15 = DS822 bit number n
# Cmd<n>DS for n = 16-31 = DS824 bit number n-16
for my $n (0 .. 15) {
  my $var = "Cmd${n}DS";
  my $src = "DS822";
  my $bit = $n;
  define_var( $var, $src, $bit );
}
for my $n (16 .. 31) {
  my $var = "Cmd${n}DS";
  my $src = "DS824";
  my $bit = $n-16;
  define_var( $var, $src, $bit );
}

# Cmd<n>S for n = 0-15 = DS844 bit number n
for my $n (0 .. 15) {
  my $var = "Cmd${n}S";
  my $src = "DS844";
  my $bit = $n;
  define_var( $var, $src, $bit );
}

# Cmd<n>S for n = 16-23 = DS860 bit number n-16
for my $n (16 .. 23) {
  my $var = "Cmd${n}S";
  my $src = "DS860";
  my $bit = $n-16;
  define_var( $var, $src, $bit );
}
