#! /bin/sh

ver=650
srcs="os fsys net gpl multicore"

# Check for source files
missing=''
for i in $srcs complete; do
  file=/fs/cd0/rtkit/$ver-$i.txt
  [ -f $file ] || missing="$missing $file"
done
if [ -n "$missing" ]; then
  echo "The following source files were not found:"
  for file in $missing; do
    echo "  $file"
  done
  exit 1
fi

for i in $srcs; do
  file=/fs/cd0/rtkit/$ver-$i.txt
  cat $file | grep -v usr/photon
done | sort -u >all.txt

cat /fs/cd0/rtkit/$ver-complete.txt | sed -e 's,^/,,' | sort -u >complete.txt
join -o 1.1 -v 1 complete.txt all.txt | grep -v opt/webkit >photon.txt

grep -v "^x86/" photon.txt >MANIFEST
grep "^x86/" photon.txt |
  sed -e 's,^x86/,,' \
    -e '\%^bin/aps% d' \
    -e '\%libham\.so% d' \
    -e '\%usr/sbin/ham% d' >MANIFEST_x86

rm all.txt complete.txt photon.txt

