#! /usr/bin/perl -w
# Responsible for generating AI.tmc and AI_col.tmc

my $srcdir = $ARGV[0];
my $odir = $srcdir || ".";
-d $srcdir || die "Source directory '$srcdir' not found\n";
open( my $tmc, '>', "$srcdir/AI.tmc" ) ||
  die "Unable to write to '$srcdir/AI.tmc'\n";
open( my $col, '>', "$srcdir/AI_col.tmc" ) ||
  die "Unable to write to '$srcdir/AI_col.tmc'\n";

print $tmc
  "%{\n  /* AI.tmc generated by gen_ai.pl */\n",
  "  #include \"subbus.h\"\n",
  "  extern unsigned short AI_buf[8];\n",
  "%}\n";
print $col
  "%{\n",
  "  /* AI_col.tmc generated by gen_ai.pl */\n",
  "  unsigned short AI_buf[8];\n",
  "  void ai_init(void) {\n",
  "    sbwr(0xC1E, 0x100);\n",
  "    sbwr(0xC5E, 0x120);\n",
  "    sbwr(0xC9E, 0x140);\n";
for my $row (0 .. 7 ) {
  for my $bank ( 0, 1 ) {
    my @group;
    for my $col (0 .. 7 ) {
      my $naddr = 0xC00 + $row*32 + $bank*16 + $col*2;
      my $addr = sprintf( "%03X", $naddr );
      my $chan = "AI$addr";
      print $tmc "TM 2 Hz AI16 $chan; Address $chan 0x$addr;\n";
      push @group, $chan;
      # my $caddr = sprintf( "%03X", $naddr+1 );
      # my $cchan = "AIC$addr";
      # print "TM 2 Hz AIC $cchan; Address $cchan 0x$caddr;\n";
      # push @group, $cchan;
    }
    print $tmc "\n%{\n  subbus_mread_req *Row${row}Bank${bank}_req;\n%}\n";
    printf $col "    Row${row}Bank${bank}_req = pack_mread_request( 8, \"%X:2:%X\" );\n",
      0xC00 + $row*32 + $bank*16, 0xC00 + $row*32 + $bank*16 + 7*2;
    print $tmc "\nGroup Row${row}Bank$bank ( ",
      join( ", ", @group ), " ) {\n",
      "  mread_subbus( Row${row}Bank${bank}_req, AI_buf );\n",
      map( "  $group[$_] = AI_buf[$_];\n", (0 .. 7) ),
      "}\n\n";
  }
}

# Three rows of muxed channels
for my $row ( 8 .. 10 ) {
  my $bank = 1;
  my @group;
  for my $col ( 0 .. 7 ) {
    my $naddr = 0xC00 + $row*32 + $bank*16 + $col*2;
    my $addr = sprintf( "%03X", $naddr );
    my $chan = "AI$addr";
    print $tmc "TM 2 Hz AI16 $chan; Address $chan 0x$addr;\n";
    push @group, $chan;
    # my $caddr = sprintf( "%03X", $naddr+1 );
    # my $cchan = "AIC$addr";
    # print "TM 1/2 Hz AIC $cchan; Address $cchan 0x$caddr;\n";
    # push @group, $cchan;
  }
  print $tmc "\n%{\n  subbus_mread_req *Mux${row}Bank{$bank}_req;\n%}\n";
  printf $col
    "    Mux${row}Bank${bank}_req = pack_mread_request( 8, \"%X:2:%X\" );\n",
    0xC00 + $row*32 + $bank*16, 0xC00 + $row*32 + $bank*16 + 7*2;
  print $tmc "\nGroup Mux${row}Bank${bank} ( ",
    join( ", ", @group ), " ) {\n",
    "  mread_subbus( Mux${row}Bank${bank}_req, AI_buf );\n",
    map( "  $group[$_] = AI_buf[$_];\n", (0 .. 7) ),
    "}\n\n";
}

print $col "  }\n%}\nTM_INIT_FUNC ai_init();\n";
close $tmc;
close $col;
