/* tm_cons.h File to be included by programs generated by TMC which
   wish to display on the console.
 * $Log$
 * Revision 1.1  1992/07/21 20:35:42  nort
 * Initial revision
 *
 */
#define display_(d,r,c,t,v,s) {\
  static t sv_;\
  if (v != sv_) { cdisplay(d,r,c,s); sv_ = v; }\
}
#define cdisplay(d,r,c,s) c_display(d,((r)*80+(c))*2,s)
void c_display(int d, int offset, char *s);
#define CONSOLE_DISPLAY
