#! /bin/sh
#  ./FullBuild all
#  ./FullBuild make
#  ./FullBuild install
function nl_error {
  echo "FullBuild: $*" >&2
  exit 1
}

function compile {
  echo
  echo "============"
  echo "$*"
  date
  id
  echo "QNX_HOST=$QNX_HOST QNX_TARGET=$QNX_TARGET"
  echo "============"
  $* || nl_error $* failed
}

case "$1" in
  make) ;;
  install) ;;
  all)
    if [ `id -u` != 0 ]; then
      exec sudo -E $0 $*
      nl_error exec failed
    fi
    if [ -n "$SUDO_USER" ]; then
      sudo -E -u $SUDO_USER $0 make || nl_error "'$0 make' failed"
    else
      $0 make || nl_error "'$0 make' failed"
    fi
    $0 install
    exit;;
  *) nl_error "usage: ./FullBuild [make|install|all]";;
esac

(
  case "$1" in
    make)
      compile autoreconf -i
      compile ./configure CPPFLAGS=-I/usr/local/include
      compile make;;
    install)
      compile make install;;
  esac
) 2>&1 | tee -a FullBuild.log
